### PR TITLE
Implement #219: Flags for ServPort and ServPortQuery

### PR DESCRIPTION
**Pull request by A-wels**
Implements #219
Added flags to msh-config.json.
Default is  set to -1, which reads the settings from server.properties.
When set to a port, msh uses these ports.

### CODE REVIEW

**Comment by A-wels** [comment]
Ok, just so I am sure that I correctly understood this correctly:
It should be possible to start msh with start parameters (e.g. ./msh --ServPort 25550)
When no parameters are given, the port is read from server.properties.

Is this correct?

**Comment by gekigek99** [comment]
Yes exactly!

Just to not overpopulate the config file with settings that 99% of users will never need.

What do you think?

**Comment by A-wels** [comment]
This does sound like a good idea. I will change this accordingly.

**Comment by A-wels** [comment]
... I just notices that the arguments are automatically written into the msh-config.json file. I will need to fix this as well

**Comment by gekigek99** [comment]
> ... I just notices that the arguments are automatically written into the msh-config.json file. I will need to fix this as well

fixed, you just forgot to remove the 2 parameters from the model config.

Good job, thanks for the help!

**Pull request merged**
